version: "3.9"

services:
  app:
    build:
      context: .  # Wskazuje na bieżący katalog zawierający Dockerfile
      dockerfile: Dockerfile
    ports:
      - "8000:8000"  # Mapowanie portu kontenera na port hosta
    environment:
      - PYTHONUNBUFFERED=1  # Zapewnia natychmiastowe wyświetlanie logów

